<?php
/**
 * Menu Functions
 *
 * These functions relate to custom menus.
 *
 * @package    Church_Theme_Framework
 * @subpackage Functions
 * @copyright  Copyright (c) 2016, churchthemes.com
 * @link       https://github.com/churchthemes/church-theme-framework
 * @license    http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 * @since      1.9.1
 */

// No direct access
if ( ! defined( 'ABSPATH' ) ) exit;

/***********************************************
 * CUSTOM MENUS
 ***********************************************/

/**
 * Fill nav menu title attribute with title
 *
 * This is useful for making bold menu links on hover that don't shift the next item
 * using this method: http://stackoverflow.com/a/20249560
 *
 * add_theme_support( 'ctfw_nav_add_title_attr' );
 *
 * @since  1.9.1
 * @param  object $sorted_menu_items Array of menu item objects before HTML is generated by wp_nav_menu()
 * @param  array $args Arguments passed to wp_nav_menu
 * @return object Modified $sorted_menu_item
 */
function ctfw_nav_add_title_attr( $sorted_menu_items, $args ) {

	// Theme supports this?
	if ( current_theme_supports( 'ctfw-nav-add-title-attr' ) ) {

		// Loop menu items
		foreach(  $sorted_menu_items as $k => $v ) {

			// Add link title value to title attribute
			$sorted_menu_items[$k]->attr_title = $v->title;

		}

	}

	return $sorted_menu_items;

}

add_filter( 'wp_nav_menu_objects', 'ctfw_nav_add_title_attr', 10, 2 );
